/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 /Users/yauheni_horbach/Documents/cv/src/ui/3d/lion/scene.glb 
Author: Khyoocumber (https://sketchfab.com/Khyoocumber)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-steampunk-lion-monster-boss-48e0aa0afcee4afe9aeed86d8fbbb579
Title: Lowpoly steampunk Lion monster boss
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lion.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -0.598]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Material_48} skeleton={nodes.Object_7.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lion.glb')
